server:
  port: 8089

spring:
  aop:
    proxy-target-class: true
  resources:
    static-locations: ["/templates/","/resources/","/static/","/public/"]
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&&serverTimezone=Asia/Shanghai
      username: root
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5


